# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udhaar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='gid',
            field=models.IntegerField(),
        ),
    ]
